name: Run Automation Tests

on:
  schedule:
    - cron: "0 * * * *"
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment: localhost / marcinkapturski.com"
        required: true
        options:
          - localhost
          - marcinkapturski.com
        default: "localhost"

jobs:
  list-specs:
    name: Files
    uses: "./.github/workflows/cy-list-of-specs.yml"

  build-packages:
    name: Build
    uses: "./.github/workflows/cy-build-packages.yml"

  run-specs:
    name: Specs
    needs: [list-specs, build-packages]
    if: always()
    uses: "./.github/workflows/cy-run-specs.yml"
    with:
      specs: ${{ needs.list-specs.outputs.specs }}
    continue-on-error: true

  report:
    name: Report
    needs: run-specs
    uses: "./.github/workflows/cy-slack-reporting.yml"
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    with:
      tests-result: ${{ needs.run-specs.result }}
