name: Run specs

on:
  workflow_call:
    inputs:
      specs:
        description: "Stringified JSON object listing specs to run"
        required: true
        type: string

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        spec: ${{ fromJson( inputs.specs ) }}
    env:
      DEFAULT_ENV: localhost
      ENV_TYPE: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ">=20.0.0"

      - name: Download the build folders
        if: ${{ github.event.inputs.environment == 'localhost' || github.event_name == 'pull_request' }}
        uses: actions/download-artifact@v4.1.7
        with:
          name: build
          path: build

      - name: Install Serve
        if: ${{ github.event.inputs.environment == 'localhost' || github.event_name == 'pull_request' }}
        run: yarn global add serve

      - name: Run application
        if: ${{ github.event.inputs.environment == 'localhost' || github.event_name == 'pull_request' }}
        run: serve -s ${{ github.workspace }}/build &

      - name: Run Tests on localhost
        if: ${{ github.event.inputs.environment == 'localhost' || github.event_name == 'pull_request' }}
        uses: cypress-io/github-action@v4
        with:
          install: true
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/${{ matrix.spec }}
          config-file: /${{ github.workspace }}/configs/localhost.config.js

      - name: Run Tests on marcinkapturski.com
        if: ${{ github.event_name == 'schedule' || github.event.inputs.environment != 'localhost' && github.event_name != 'pull_request' }}
        uses: cypress-io/github-action@v4
        with:
          install: true
          browser: chrome
          spec: cypress/${{ matrix.spec }}
          config-file: /${{ github.workspace }}/configs/marcinkapturski.config.js

      - name: Clean up build folder
        uses: geekyeggo/delete-artifact@v4
        with:
          name: build
