name: Report test results on Slack

on:
  workflow_call:

jobs:
  report:
    name: Report results on Slack
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Slack notification
        if: always()
        run: |
          export SCRIPT_PATH=${{ github.workspace }}/cypress/slack/message.js
          yarn node $SCRIPT_PATH
