name: Slack notification

on:
  workflow_call:
    inputs:
      tests-result:
        required: true
        type: string
        description: "Test run status"
    secrets:
      SLACK_WEBHOOK:
        required: true

jobs:
  report:
    name: Report results on Slack
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout the repository
        if: always()
        uses: actions/checkout@v3

      - name: Install Node.js
        if: always()
        uses: actions/setup-node@v3
        with:
          node-version: ">=16.0.0"

      - name: install dependency
        if: always()
        run: |
          yarn add isomorphic-fetch

      - name: Slack (${{ inputs.tests-result }}) notification
        if: always()
        run: |
          export SCRIPT_PATH=${{ github.workspace }}/cypress/slack/${{ inputs.tests-result == 'success' && 'success_message.js' || 'failed_message.js'}}
          yarn node $SCRIPT_PATH "${{ secrets.SLACK_WEBHOOK }}"
