name: Slack notification

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK:
        required: true

jobs:
  report:
    name: Report results on Slack
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Slack notification
        if: always()
        run: |
          export SCRIPT_PATH=${{ github.workspace }}/cypress/slack/message.js
          yarn node $SCRIPT_PATH "${{ secrets.SLACK_WEBHOOK }}"
